import {isLuhnValid} from "./card-luhn"; import type {Detection} from "./types";
const patterns=[
 {kind:"EMAIL", sensitivity:"HIGH", re:/\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}\b/gi},
 {kind:"PHONE", sensitivity:"HIGH", re:/(?<!\d)(?:\+91[- ]?)?[6-9]\d{9}(?!\d)/g},
 {kind:"CARD", sensitivity:"HIGH", re:/(?<!\d)(?:(?:\d{4}[ -]){3}\d{4}|\d{13,19})(?!\d)/g},
 {kind:"PASSWORD", sensitivity:"CRITICAL", re:/\b(?:sk|pk|api|access|auth)[_-][A-Za-z0-9_-]{12,}\b/gi}
] as const;
export function detectStructuredPii(text:string):Detection[]{const out:Detection[]=[]; for(const p of patterns){p.re.lastIndex=0; let m; while((m=p.re.exec(text))){if(p.kind==="CARD"&&!isLuhnValid(m[0]))continue;out.push({kind:p.kind,sensitivity:p.sensitivity,value:m[0],start:m.index,end:m.index+m[0].length,source:"RULE"});}}return out;}
const vd=[[0,1,2,3,4,5,6,7,8,9],[1,2,3,4,0,6,7,8,9,5],[2,3,4,0,1,7,8,9,5,6],[3,4,0,1,2,8,9,5,6,7],[4,0,1,2,3,9,5,6,7,8],[5,9,8,7,6,0,4,3,2,1],[6,5,9,8,7,1,0,4,3,2],[7,6,5,9,8,2,1,0,4,3],[8,7,6,5,9,3,2,1,0,4],[9,8,7,6,5,4,3,2,1,0]];
const vp=[[0,1,2,3,4,5,6,7,8,9],[1,5,7,6,2,8,3,0,9,4],[5,8,0,3,7,9,6,1,4,2],[8,9,1,6,0,4,3,5,2,7],[9,4,5,3,1,2,6,8,7,0],[4,2,8,6,5,7,3,9,0,1],[2,7,9,3,8,0,6,4,1,5],[7,0,4,6,9,1,3,2,5,8]];
const validVerhoeff=(raw:string)=>{const digits=raw.replace(/\D/g,"");if(!/^\d{12}$/.test(digits))return false;let c=0;for(let i=0;i<digits.length;i++)c=vd[c]![vp[i%8]![Number(digits[digits.length-1-i])]!]!;return c===0};
export const highEntropySecret=(value:string)=>value.length>=16&&/[a-z]/.test(value)&&/[A-Z]/.test(value)&&/\d/.test(value)&&new Set(value).size>=10;
export function detectSensitiveField(input:{type?:string;autocomplete?:string;label?:string;value?:string}):Detection[]{const semantic=`${input.type} ${input.autocomplete} ${input.label}`.toLowerCase(); const value=input.value??""; let kind:Detection["kind"]|undefined;if(/password/.test(semantic))kind="PASSWORD";else if(/one-time-code|\botp\b/.test(semantic))kind="OTP";else if(/\bcvv|cvc|cc-csc/.test(semantic))kind="CVV";else if(/\bpin\b/.test(semantic))kind="PIN";else if(/cc-number|card(?: number)?|credit.?card/.test(semantic))kind="CARD";else if(/\b(pan|tax id|income tax)\b/.test(semantic)&&/^[A-Z]{5}\d{4}[A-Z]$/i.test(value.replace(/\s/g,"")))kind="GOV_ID";else if(/aadhaar|aadhar|uidai/.test(semantic)&&validVerhoeff(value))kind="GOV_ID";else if(/api.?key|access.?token|auth.?token|client.?secret/.test(semantic)&&highEntropySecret(value))kind="PASSWORD";else if(/email/.test(semantic))kind="EMAIL";else if(/tel|phone/.test(semantic))kind="PHONE";return kind?[{kind,sensitivity:["PASSWORD","OTP","CVV","PIN"].includes(kind)?"CRITICAL":"HIGH",value,source:"DOM"}]:detectStructuredPii(value)}