import {detectStructuredPii} from "./detectors";
export type BlockReason="UNKNOWN_PROPERTY"|"RAW_CAPTURE_TYPE"|"UNSANITIZED_IMAGE"|"PLAINTEXT_SECRET"|"PII_RESCAN_HIT"|"URL_QUERY_PRESENT"|"VAULT_SHAPE_DETECTED"|"PAYLOAD_TOO_LARGE"|"INVALID_SCHEMA"|"PRIVACY_ENGINE_UNAVAILABLE";
export interface SanitizedObservation{schemaVersion:"1.0";sessionId:string;stepId:number;observationVersion:string;goal:string;page:{origin:string;title:string};elements:Array<{id:string;role:string;label?:string;value?:string;enabled:boolean;visible:boolean;source:"DOM"|"VISUAL"|"MERGED"}>;redaction:{count:number;sanitizedImageSha256:string}}
export interface SanitizedImage{kind:"SANITIZED_CAPTURE";bytes:Uint8Array;sha256:string}
const keys={root:["schemaVersion","sessionId","stepId","observationVersion","goal","page","elements","redaction"],page:["origin","title"],element:["id","role","label","value","enabled","visible","source"],redaction:["count","sanitizedImageSha256"]};
const unknown=(o:object,allowed:string[])=>Object.keys(o).some(k=>!allowed.includes(k)); const walk=(x:unknown):string[]=>typeof x==="string"?[x]:Array.isArray(x)?x.flatMap(walk):x&&typeof x==="object"?Object.values(x).flatMap(walk):[];
export function approveForEgress(c:unknown,image:unknown,max=262144):{ok:true;value:{metadata:SanitizedObservation;image:SanitizedImage}}|{ok:false;code:BlockReason}{
 if(!c||typeof c!=="object"||Array.isArray(c))return{ok:false,code:"INVALID_SCHEMA"};const v=c as SanitizedObservation;
 if(unknown(v,keys.root))return{ok:false,code:"UNKNOWN_PROPERTY"};if(!v.page||unknown(v.page,keys.page)||!Array.isArray(v.elements)||v.elements.some(e=>unknown(e,keys.element))||!v.redaction||unknown(v.redaction,keys.redaction))return{ok:false,code:"UNKNOWN_PROPERTY"};
 if(v.schemaVersion!=="1.0"||typeof v.goal!=="string"||typeof v.page.origin!=="string")return{ok:false,code:"INVALID_SCHEMA"};try{const u=new URL(v.page.origin);if(u.pathname!=="/"||u.search||u.hash)return{ok:false,code:"URL_QUERY_PRESENT"}}catch{return{ok:false,code:"INVALID_SCHEMA"}}
 if(walk(v).some(s=>detectStructuredPii(s).length>0))return{ok:false,code:"PII_RESCAN_HIT"}; if(walk(v).some(s=>/password|expiresAt|allowedFieldRoles/i.test(s)))return{ok:false,code:"VAULT_SHAPE_DETECTED"};
 if(new TextEncoder().encode(JSON.stringify(v)).length>max)return{ok:false,code:"PAYLOAD_TOO_LARGE"}; if(!image||typeof image!=="object"||(image as SanitizedImage).kind!=="SANITIZED_CAPTURE")return{ok:false,code:"RAW_CAPTURE_TYPE"};const im=image as SanitizedImage;if(im.sha256!==v.redaction.sanitizedImageSha256)return{ok:false,code:"UNSANITIZED_IMAGE"};return{ok:true,value:{metadata:v,image:im}}}
