import type {Sensitivity,TokenKind} from "./types";
export type VaultToken=`[${TokenKind}_${number}]`; export interface VaultContext{sessionId:string;tabId:number;origin:string;fieldRole:string;sourceElementId:string}
interface Entry{token:VaultToken;value:string;kind:TokenKind;sensitivity:Sensitivity;sessionId:string;tabId:number;origin:string;expiresAt:number;allowedFieldRoles:string[];sourceElementId:string}
export interface VaultStore{get(key:string):Promise<Entry[]|undefined>;set(key:string,value:Entry[]):Promise<void>;remove(key:string):Promise<void>}
export class MemoryVaultStore implements VaultStore{private m=new Map<string,Entry[]>();async get(k:string){return this.m.get(k)}async set(k:string,v:Entry[]){this.m.set(k,v)}async remove(k:string){this.m.delete(k)}}
export class TokenVault{constructor(private store:VaultStore=new MemoryVaultStore(),private now=()=>Date.now()){} private key(s:string){return `privsight:vault:${s}`}
 async put(x:Omit<Entry,"token">):Promise<VaultToken>{if(x.kind==="CARD"||x.kind==="CVV")throw new Error("UNSUPPORTED_PAYMENT_TOKEN");const k=this.key(x.sessionId), entries=(await this.store.get(k))??[]; const duplicate=entries.find(e=>e.kind===x.kind&&e.value===x.value&&e.tabId===x.tabId&&e.origin===x.origin&&e.sourceElementId===x.sourceElementId&&e.allowedFieldRoles.join("\0")===x.allowedFieldRoles.join("\0"));if(duplicate)return duplicate.token;const token=`[${x.kind}_${entries.filter(e=>e.kind===x.kind).length+1}]` as VaultToken; await this.store.set(k,[...entries,{...x,token}]);return token}
 async issuedTokens(sessionId:string):Promise<Set<VaultToken>>{return new Set(((await this.store.get(this.key(sessionId)))??[]).map(entry=>entry.token))}
 async resolveForAction(token:VaultToken,c:VaultContext){const e=((await this.store.get(this.key(c.sessionId)))??[]).find(x=>x.token===token);if(!e)throw new Error("TOKEN_NOT_FOUND");if(e.expiresAt<=this.now())throw new Error("TOKEN_EXPIRED");if(e.tabId!==c.tabId||e.origin!==c.origin)throw new Error("TOKEN_SCOPE_MISMATCH");if(!e.allowedFieldRoles.includes(c.fieldRole))throw new Error("TOKEN_FIELD_MISMATCH");if(e.sourceElementId!==c.sourceElementId)throw new Error("TOKEN_ELEMENT_MISMATCH");if(e.kind==="CARD"||e.kind==="CVV")throw new Error("UNSUPPORTED_PAYMENT_EXECUTION");return e.value} async purgeSession(s:string){await this.store.remove(this.key(s))}}
export class ChromeSessionStore implements VaultStore{async get(k:string):Promise<Entry[]|undefined>{return (await browser.storage.session.get(k))[k] as Entry[]|undefined}async set(k:string,v:Entry[]){await browser.storage.session.set({[k]:v})}async remove(k:string){await browser.storage.session.remove(k)}}